[v1]
"abscissa 0.5.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["abscissa"]
"ag 0.15.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["agrind"]
"bandwhich 0.20.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["bandwhich"]
"bat 0.17.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["bat"]
"broot 1.0.8 (registry+https://github.com/rust-lang/crates.io-index)" = ["broot"]
"cargo-audit 0.13.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-audit"]
"cargo-authors 0.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-authors"]
"cargo-benchcmp 0.4.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-benchcmp"]
"cargo-bump 1.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-bump"]
"cargo-cli 1.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-cli"]
"cargo-clone 0.1.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-clone"]
"cargo-config 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-config"]
"cargo-cook 1.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-cook"]
"cargo-count 0.2.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-count"]
"cargo-ctags 0.2.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-ctags"]
"cargo-deadlinks 0.7.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-deadlinks", "deadlinks"]
"cargo-do 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-do"]
"cargo-edit 0.7.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-add", "cargo-rm", "cargo-upgrade"]
"cargo-edit-locally 0.1.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-edit-locally"]
"cargo-expand 1.0.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-expand"]
"cargo-info 0.5.14 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-info"]
"cargo-license 0.3.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-license"]
"cargo-lichking 0.9.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-lichking"]
"cargo-modules 0.4.9 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-modules"]
"cargo-outdated 0.9.13 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-outdated"]
"cargo-readme 3.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-readme"]
"cargo-release 0.13.9 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-release"]
"cargo-show 0.5.9 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-show"]
"cargo-update 5.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-install-update", "cargo-install-update-config"]
"cargo-watch 7.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-watch"]
"chars 0.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["chars"]
"dotenv-linter 2.2.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["dotenv-linter"]
"du-dust 0.5.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["dust"]
"eva 0.2.7 (registry+https://github.com/rust-lang/crates.io-index)" = ["eva"]
"exa 0.9.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["exa"]
"fd-find 8.2.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["fd"]
"git-brws 0.11.12 (registry+https://github.com/rust-lang/crates.io-index)" = ["git-brws"]
"git-historian 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["git-historian"]
"git-journal 1.8.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["git-journal"]
"gitui 0.10.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["gitui"]
"gping 1.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["gping"]
"grex 1.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["grex"]
"hexyl 0.8.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["hexyl"]
"ht 0.6.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["ht"]
"hyperfine 1.11.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["hyperfine"]
"just 0.8.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["just"]
"loop-rs 0.6.1 (path+file:///Users/austin/mess/2019/23/Loop)" = ["loop"]
"mdcat 0.22.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["mdcat"]
"procs 0.10.10 (registry+https://github.com/rust-lang/crates.io-index)" = ["procs"]
"racer 2.1.39 (registry+https://github.com/rust-lang/crates.io-index)" = ["racer"]
"rage 0.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rage", "rage-keygen"]
"ripgrep 12.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["rg"]
"sd 0.7.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["sd"]
"skim 0.9.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["sk"]
"starship 0.47.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["starship"]
"svgbob_cli 0.4.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["svgbob"]
"taplo-cli 0.3.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["taplo"]
"tealdeer 1.4.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["tldr"]
"titlecase 1.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["titlecase"]
"tokei 12.0.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["tokei"]
"toml-fmt 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["toml-fmt"]
"watchexec 1.14.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["watchexec"]
"xsv 0.13.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["xsv"]
"ytop 0.6.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["ytop"]
"zoxide 0.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["zoxide"]
